[package]
name = "stylized-dhbw"
version = "1.0.0"
entrypoint = "lib.typ"
authors = [ "Finn Hannon <@Ohannain>" ]
license = "MIT"
description = "Unofficial, modern, simplistic and stylized template for use at DHBW."
repository = "https://github.com/Ohannain/dhbw-typst-template"
keywords = [ "dhbw", "thesis", "duale hochschule baden-württemberg" ]
categories = [ "paper", "thesis", "report" ]
disciplines = [ "computer-science", "engineering" ]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
